/**
 * ChallanCard - Displays a simulated e-challan.
 */
import React from 'react';

export default function ChallanCard({ challan }) {
  if (!challan) return null;

  return (
    <div
      style={{
        background: 'var(--bg-card)',
        border: '1px solid rgba(245, 158, 11, 0.3)',
        borderRadius: '12px',
        padding: '20px',
        animation: 'slide-up 0.3s ease',
      }}
    >
      {/* Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: '16px',
        paddingBottom: '12px',
        borderBottom: '1px solid var(--border-color)',
      }}>
        <div>
          <div style={{ fontSize: '10px', color: 'var(--accent-amber)', fontWeight: 700, letterSpacing: '1px', marginBottom: '4px' }}>
            ⚠️ SIMULATED E-CHALLAN
          </div>
          <div style={{ fontSize: '18px', fontWeight: 800, fontFamily: 'monospace', color: 'var(--accent-amber)' }}>
            {challan.challan_id}
          </div>
        </div>
        <span className="badge badge-amber">
          {challan.status}
        </span>
      </div>

      {/* Details */}
      <div style={{ display: 'grid', gap: '8px', fontSize: '13px' }}>
        <Row label="Vehicle Number" value={challan.vehicle_number || 'UNKNOWN'} mono />
        <Row label="Vehicle Type" value={challan.vehicle_type || 'Unknown'} />
        <Row label="Violation" value={challan.violation_type} />
        <Row label="Date/Time" value={challan.timestamp ? new Date(challan.timestamp).toLocaleString() : 'N/A'} />
        <Row label="Location" value={
          challan.location_lat
            ? `${challan.location_lat?.toFixed(4)}, ${challan.location_lon?.toFixed(4)}`
            : 'N/A'
        } />
        <Row label="Emergency Event" value={challan.emergency_event_id} mono />
        <Row label="Violation Ref" value={challan.violation_id} mono />
        {challan.confidence_score && (
          <Row label="Confidence" value={`${(challan.confidence_score * 100).toFixed(0)}%`} />
        )}
      </div>

      {/* Disclaimer */}
      <div style={{
        marginTop: '16px',
        padding: '10px',
        background: 'rgba(245, 158, 11, 0.06)',
        borderRadius: '8px',
        fontSize: '10px',
        color: 'var(--text-muted)',
        lineHeight: 1.5,
        border: '1px solid rgba(245, 158, 11, 0.15)',
      }}>
        <strong style={{ color: 'var(--accent-amber)' }}>DISCLAIMER:</strong> This is a simulated
        e-challan generated by the Smart Ambulance Emergency Corridor prototype system. No legally
        valid government challan has been issued. This record is for demonstration purposes only.
      </div>
    </div>
  );
}

function Row({ label, value, mono }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
      <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
      <span style={{
        fontWeight: 600,
        fontFamily: mono ? 'monospace' : 'inherit',
        textTransform: mono ? 'none' : 'capitalize',
      }}>
        {value}
      </span>
    </div>
  );
}
