"""
EmergencyCorridorRecord
-----------------------
Persistent record for every emergency green corridor created by a driver.

Status lifecycle:
  ACTIVE → COMPLETED | CLOSED

Written by:  EmergencyCorridorService.start() / _finish_corridor() / reset()
Read by:     /dashboard (active corridors count, recent corridors list)
             /emergency-corridor  (admin list page)
             /emergency-corridor/<corridor_id>  (detail page)
             /report  (emergency response section)
"""

from datetime import datetime
from app.extensions import db


class EmergencyCorridorRecord(db.Model):
    __tablename__ = "emergency_corridors"

    id                   = db.Column(db.Integer, primary_key=True, autoincrement=True)
    corridor_id          = db.Column(db.String(20), unique=True, nullable=False, index=True)
    # Short human-readable ID generated by the service, e.g. "A3F7B2"

    # Route endpoints
    source_name          = db.Column(db.String(255), nullable=False)
    source_lat           = db.Column(db.Float, nullable=True)
    source_lon           = db.Column(db.Float, nullable=True)
    destination_name     = db.Column(db.String(255), nullable=False)
    destination_lat      = db.Column(db.Float, nullable=True)
    destination_lon      = db.Column(db.Float, nullable=True)

    # Route identity (matches routes.json route_id)
    route_id             = db.Column(db.String(60), nullable=True)

    # Metrics
    distance_km               = db.Column(db.Float, nullable=True)
    baseline_eta_minutes      = db.Column(db.Float, nullable=True)
    optimized_eta_minutes     = db.Column(db.Float, nullable=True)
    time_saved_minutes        = db.Column(db.Float, nullable=True)

    # Status
    status               = db.Column(db.String(20), nullable=False, default="ACTIVE", index=True)
    # "ACTIVE" | "COMPLETED" | "CLOSED"

    # Timestamps
    started_at           = db.Column(db.DateTime, nullable=True)
    completed_at         = db.Column(db.DateTime, nullable=True)
    created_at           = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)

    # Relationships
    events   = db.relationship("EmergencyCorridorEvent", back_populates="corridor",
                               cascade="all, delete-orphan", lazy="dynamic",
                               order_by="EmergencyCorridorEvent.created_at")
    anpr     = db.relationship("ANPRDetection", back_populates="corridor",
                               cascade="all, delete-orphan", lazy="dynamic",
                               order_by="ANPRDetection.detected_at")
    metrics  = db.relationship("EmergencyMetrics", back_populates="corridor",
                               uselist=False, cascade="all, delete-orphan")

    def __repr__(self):
        return (f"<EmergencyCorridorRecord {self.corridor_id} "
                f"{self.source_name}→{self.destination_name} [{self.status}]>")
